// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protocol_v3.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Protocol_v3.proto</summary>
public static partial class ProtocolV3Reflection
{

    #region Descriptor
    /// <summary>File descriptor for Protocol_v3.proto</summary>
    public static pbr::FileDescriptor Descriptor
    {
        get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtocolV3Reflection()
    {
        byte[] descriptorData = global::System.Convert.FromBase64String(
            string.Concat(
              "ChFQcm90b2NvbF92My5wcm90byIqCgRVc2VyEhAKCHVzZXJuYW1lGAEgASgJ",
              "EhAKCHBhc3N3b3JkGAIgASgJIiIKBUNoaWxkEgwKBG5hbWUYASABKAkSCwoD",
              "YWdlGAIgASgFImIKFVBhcnRpY2lwYW50RGV0YWlsc0RUTxIMCgRuYW1lGAEg",
              "ASgJEgsKA2FnZRgCIAEoBRIWCgZldmVudDEYAyABKA4yBi5FdmVudBIWCgZl",
              "dmVudDIYBCABKA4yBi5FdmVudCI7ChBDaGlsZE5vRXZlbnRzRFRPEhUKBWNo",
              "aWxkGAEgASgLMgYuQ2hpbGQSEAoIbm9FdmVudHMYAiABKAUiRgoQRXZlbnRB",
              "Z2VHcm91cERUTxIVCgVldmVudBgBIAEoDjIGLkV2ZW50EhsKCGFnZUdyb3Vw",
              "GAIgASgOMgkuQWdlR3JvdXAiUgoNRXZlbnRDb3VudERUTxIVCgVldmVudBgB",
              "IAEoDjIGLkV2ZW50EhsKCGFnZUdyb3VwGAIgASgOMgkuQWdlR3JvdXASDQoF",
              "Y291bnQYAyABKAMi5gEKB1JlcXVlc3QSGwoEdHlwZRgBIAEoDjINLlJlcXVl",
              "c3QuVHlwZRITCgR1c2VyGAIgASgLMgUuVXNlchIeCgNlYWcYAyABKAsyES5F",
              "dmVudEFnZUdyb3VwRFRPEiIKAnBkGAQgASgLMhYuUGFydGljaXBhbnREZXRh",
              "aWxzRFRPImUKBFR5cGUSCwoHVU5LTk9XThAAEgkKBUxPR0lOEAESCgoGTE9H",
              "T1VUEAISEwoPQ0hJTERSRU5fRVZFTlRTEAMSEwoPQUREX1BBUlRJQ0lQQU5U",
              "EAQSDwoLRVZFTlRfQ09VTlQQBSLVAQoIUmVzcG9uc2USHAoEdHlwZRgBIAEo",
              "DjIOLlJlc3BvbnNlLlR5cGUSDQoFZXJyb3IYAiABKAkSGgoCZWMYAyADKAsy",
              "Di5FdmVudENvdW50RFRPEh4KA2NuZRgEIAMoCzIRLkNoaWxkTm9FdmVudHNE",
              "VE8iYAoEVHlwZRILCgdVTktOT1dOEAASBgoCT0sQARIJCgVFUlJPUhACEhMK",
              "D0NISUxEUkVOX0VWRU5UUxADEg8KC0VWRU5UX0NPVU5UEAQSEgoOUkVGUkVT",
              "SF9FVkVOVFMQBSo+CgVFdmVudBIICgROT05FEAASCAoERTUwTRABEgkKBUUx",
              "MDBNEAISCgoGRTEwMDBNEAMSCgoGRTE1MDBNEAQqLgoIQWdlR3JvdXASCQoF",
              "QTZfOFkQABIKCgZBOV8xMVkQARILCgdBMTJfMTVZEAJCCkIIUHJvdG9idWZi",
              "BnByb3RvMw=="));
        descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
            new pbr::FileDescriptor[] { },
            new pbr::GeneratedClrTypeInfo(new[] { typeof(global::Event), typeof(global::AgeGroup), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::User), global::User.Parser, new[]{ "Username", "Password" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Child), global::Child.Parser, new[]{ "Name", "Age" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ParticipantDetailsDTO), global::ParticipantDetailsDTO.Parser, new[]{ "Name", "Age", "Event1", "Event2" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ChildNoEventsDTO), global::ChildNoEventsDTO.Parser, new[]{ "Child", "NoEvents" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::EventAgeGroupDTO), global::EventAgeGroupDTO.Parser, new[]{ "Event", "AgeGroup" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::EventCountDTO), global::EventCountDTO.Parser, new[]{ "Event", "AgeGroup", "Count" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Request), global::Request.Parser, new[]{ "Type", "User", "Eag", "Pd" }, null, new[]{ typeof(global::Request.Types.Type) }, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Response), global::Response.Parser, new[]{ "Type", "Error", "Ec", "Cne" }, null, new[]{ typeof(global::Response.Types.Type) }, null, null)
            }));
    }
    #endregion

}
#region Enums
public enum Event
{
    [pbr::OriginalName("NONE")] None = 0,
    [pbr::OriginalName("E50M")] E50M = 1,
    [pbr::OriginalName("E100M")] E100M = 2,
    [pbr::OriginalName("E1000M")] E1000M = 3,
    [pbr::OriginalName("E1500M")] E1500M = 4,
}

public enum AgeGroup
{
    [pbr::OriginalName("A6_8Y")] A68Y = 0,
    [pbr::OriginalName("A9_11Y")] A911Y = 1,
    [pbr::OriginalName("A12_15Y")] A1215Y = 2,
}

#endregion

#region Messages
public sealed partial class User : pb::IMessage<User>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
    private static readonly pb::MessageParser<User> _parser = new pb::MessageParser<User>(() => new User());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<User> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor
    {
        get { return global::ProtocolV3Reflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor
    {
        get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public User()
    {
        OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public User(User other) : this()
    {
        username_ = other.username_;
        password_ = other.password_;
        _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public User Clone()
    {
        return new User(this);
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 1;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Username
    {
        get { return username_; }
        set
        {
            username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 2;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Password
    {
        get { return password_; }
        set
        {
            password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other)
    {
        return Equals(other as User);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(User other)
    {
        if (ReferenceEquals(other, null))
        {
            return false;
        }
        if (ReferenceEquals(other, this))
        {
            return true;
        }
        if (Username != other.Username) return false;
        if (Password != other.Password) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode()
    {
        int hash = 1;
        if (Username.Length != 0) hash ^= Username.GetHashCode();
        if (Password.Length != 0) hash ^= Password.GetHashCode();
        if (_unknownFields != null)
        {
            hash ^= _unknownFields.GetHashCode();
        }
        return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString()
    {
        return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output)
    {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        output.WriteRawMessage(this);
#else
    if (Username.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Username);
    }
    if (Password.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Password);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
    {
        if (Username.Length != 0)
        {
            output.WriteRawTag(10);
            output.WriteString(Username);
        }
        if (Password.Length != 0)
        {
            output.WriteRawTag(18);
            output.WriteString(Password);
        }
        if (_unknownFields != null)
        {
            _unknownFields.WriteTo(ref output);
        }
    }
#endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize()
    {
        int size = 0;
        if (Username.Length != 0)
        {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
        }
        if (Password.Length != 0)
        {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
        }
        if (_unknownFields != null)
        {
            size += _unknownFields.CalculateSize();
        }
        return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(User other)
    {
        if (other == null)
        {
            return;
        }
        if (other.Username.Length != 0)
        {
            Username = other.Username;
        }
        if (other.Password.Length != 0)
        {
            Password = other.Password;
        }
        _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input)
    {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        input.ReadRawMessage(this);
#else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Username = input.ReadString();
          break;
        }
        case 18: {
          Password = input.ReadString();
          break;
        }
      }
    }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                    break;
                case 10:
                    {
                        Username = input.ReadString();
                        break;
                    }
                case 18:
                    {
                        Password = input.ReadString();
                        break;
                    }
            }
        }
    }
#endif

}

public sealed partial class Child : pb::IMessage<Child>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
    private static readonly pb::MessageParser<Child> _parser = new pb::MessageParser<Child>(() => new Child());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Child> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor
    {
        get { return global::ProtocolV3Reflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor
    {
        get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Child()
    {
        OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Child(Child other) : this()
    {
        name_ = other.name_;
        age_ = other.age_;
        _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Child Clone()
    {
        return new Child(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name
    {
        get { return name_; }
        set
        {
            name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        }
    }

    /// <summary>Field number for the "age" field.</summary>
    public const int AgeFieldNumber = 2;
    private int age_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Age
    {
        get { return age_; }
        set
        {
            age_ = value;
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other)
    {
        return Equals(other as Child);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Child other)
    {
        if (ReferenceEquals(other, null))
        {
            return false;
        }
        if (ReferenceEquals(other, this))
        {
            return true;
        }
        if (Name != other.Name) return false;
        if (Age != other.Age) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode()
    {
        int hash = 1;
        if (Name.Length != 0) hash ^= Name.GetHashCode();
        if (Age != 0) hash ^= Age.GetHashCode();
        if (_unknownFields != null)
        {
            hash ^= _unknownFields.GetHashCode();
        }
        return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString()
    {
        return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output)
    {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        output.WriteRawMessage(this);
#else
    if (Name.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Name);
    }
    if (Age != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Age);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
    {
        if (Name.Length != 0)
        {
            output.WriteRawTag(10);
            output.WriteString(Name);
        }
        if (Age != 0)
        {
            output.WriteRawTag(16);
            output.WriteInt32(Age);
        }
        if (_unknownFields != null)
        {
            _unknownFields.WriteTo(ref output);
        }
    }
#endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize()
    {
        int size = 0;
        if (Name.Length != 0)
        {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
        }
        if (Age != 0)
        {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Age);
        }
        if (_unknownFields != null)
        {
            size += _unknownFields.CalculateSize();
        }
        return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Child other)
    {
        if (other == null)
        {
            return;
        }
        if (other.Name.Length != 0)
        {
            Name = other.Name;
        }
        if (other.Age != 0)
        {
            Age = other.Age;
        }
        _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input)
    {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        input.ReadRawMessage(this);
#else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Name = input.ReadString();
          break;
        }
        case 16: {
          Age = input.ReadInt32();
          break;
        }
      }
    }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                    break;
                case 10:
                    {
                        Name = input.ReadString();
                        break;
                    }
                case 16:
                    {
                        Age = input.ReadInt32();
                        break;
                    }
            }
        }
    }
#endif

}

public sealed partial class ParticipantDetailsDTO : pb::IMessage<ParticipantDetailsDTO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
    private static readonly pb::MessageParser<ParticipantDetailsDTO> _parser = new pb::MessageParser<ParticipantDetailsDTO>(() => new ParticipantDetailsDTO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ParticipantDetailsDTO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor
    {
        get { return global::ProtocolV3Reflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor
    {
        get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ParticipantDetailsDTO()
    {
        OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ParticipantDetailsDTO(ParticipantDetailsDTO other) : this()
    {
        name_ = other.name_;
        age_ = other.age_;
        event1_ = other.event1_;
        event2_ = other.event2_;
        _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ParticipantDetailsDTO Clone()
    {
        return new ParticipantDetailsDTO(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name
    {
        get { return name_; }
        set
        {
            name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        }
    }

    /// <summary>Field number for the "age" field.</summary>
    public const int AgeFieldNumber = 2;
    private int age_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Age
    {
        get { return age_; }
        set
        {
            age_ = value;
        }
    }

    /// <summary>Field number for the "event1" field.</summary>
    public const int Event1FieldNumber = 3;
    private global::Event event1_ = global::Event.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Event Event1
    {
        get { return event1_; }
        set
        {
            event1_ = value;
        }
    }

    /// <summary>Field number for the "event2" field.</summary>
    public const int Event2FieldNumber = 4;
    private global::Event event2_ = global::Event.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Event Event2
    {
        get { return event2_; }
        set
        {
            event2_ = value;
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other)
    {
        return Equals(other as ParticipantDetailsDTO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ParticipantDetailsDTO other)
    {
        if (ReferenceEquals(other, null))
        {
            return false;
        }
        if (ReferenceEquals(other, this))
        {
            return true;
        }
        if (Name != other.Name) return false;
        if (Age != other.Age) return false;
        if (Event1 != other.Event1) return false;
        if (Event2 != other.Event2) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode()
    {
        int hash = 1;
        if (Name.Length != 0) hash ^= Name.GetHashCode();
        if (Age != 0) hash ^= Age.GetHashCode();
        if (Event1 != global::Event.None) hash ^= Event1.GetHashCode();
        if (Event2 != global::Event.None) hash ^= Event2.GetHashCode();
        if (_unknownFields != null)
        {
            hash ^= _unknownFields.GetHashCode();
        }
        return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString()
    {
        return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output)
    {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        output.WriteRawMessage(this);
#else
    if (Name.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Name);
    }
    if (Age != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Age);
    }
    if (Event1 != global::Event.None) {
      output.WriteRawTag(24);
      output.WriteEnum((int) Event1);
    }
    if (Event2 != global::Event.None) {
      output.WriteRawTag(32);
      output.WriteEnum((int) Event2);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
    {
        if (Name.Length != 0)
        {
            output.WriteRawTag(10);
            output.WriteString(Name);
        }
        if (Age != 0)
        {
            output.WriteRawTag(16);
            output.WriteInt32(Age);
        }
        if (Event1 != global::Event.None)
        {
            output.WriteRawTag(24);
            output.WriteEnum((int)Event1);
        }
        if (Event2 != global::Event.None)
        {
            output.WriteRawTag(32);
            output.WriteEnum((int)Event2);
        }
        if (_unknownFields != null)
        {
            _unknownFields.WriteTo(ref output);
        }
    }
#endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize()
    {
        int size = 0;
        if (Name.Length != 0)
        {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
        }
        if (Age != 0)
        {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Age);
        }
        if (Event1 != global::Event.None)
        {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int)Event1);
        }
        if (Event2 != global::Event.None)
        {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int)Event2);
        }
        if (_unknownFields != null)
        {
            size += _unknownFields.CalculateSize();
        }
        return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ParticipantDetailsDTO other)
    {
        if (other == null)
        {
            return;
        }
        if (other.Name.Length != 0)
        {
            Name = other.Name;
        }
        if (other.Age != 0)
        {
            Age = other.Age;
        }
        if (other.Event1 != global::Event.None)
        {
            Event1 = other.Event1;
        }
        if (other.Event2 != global::Event.None)
        {
            Event2 = other.Event2;
        }
        _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input)
    {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        input.ReadRawMessage(this);
#else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Name = input.ReadString();
          break;
        }
        case 16: {
          Age = input.ReadInt32();
          break;
        }
        case 24: {
          Event1 = (global::Event) input.ReadEnum();
          break;
        }
        case 32: {
          Event2 = (global::Event) input.ReadEnum();
          break;
        }
      }
    }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                    break;
                case 10:
                    {
                        Name = input.ReadString();
                        break;
                    }
                case 16:
                    {
                        Age = input.ReadInt32();
                        break;
                    }
                case 24:
                    {
                        Event1 = (global::Event)input.ReadEnum();
                        break;
                    }
                case 32:
                    {
                        Event2 = (global::Event)input.ReadEnum();
                        break;
                    }
            }
        }
    }
#endif

}

public sealed partial class ChildNoEventsDTO : pb::IMessage<ChildNoEventsDTO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
    private static readonly pb::MessageParser<ChildNoEventsDTO> _parser = new pb::MessageParser<ChildNoEventsDTO>(() => new ChildNoEventsDTO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ChildNoEventsDTO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor
    {
        get { return global::ProtocolV3Reflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor
    {
        get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChildNoEventsDTO()
    {
        OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChildNoEventsDTO(ChildNoEventsDTO other) : this()
    {
        child_ = other.child_ != null ? other.child_.Clone() : null;
        noEvents_ = other.noEvents_;
        _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChildNoEventsDTO Clone()
    {
        return new ChildNoEventsDTO(this);
    }

    /// <summary>Field number for the "child" field.</summary>
    public const int ChildFieldNumber = 1;
    private global::Child child_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Child Child
    {
        get { return child_; }
        set
        {
            child_ = value;
        }
    }

    /// <summary>Field number for the "noEvents" field.</summary>
    public const int NoEventsFieldNumber = 2;
    private int noEvents_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int NoEvents
    {
        get { return noEvents_; }
        set
        {
            noEvents_ = value;
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other)
    {
        return Equals(other as ChildNoEventsDTO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ChildNoEventsDTO other)
    {
        if (ReferenceEquals(other, null))
        {
            return false;
        }
        if (ReferenceEquals(other, this))
        {
            return true;
        }
        if (!object.Equals(Child, other.Child)) return false;
        if (NoEvents != other.NoEvents) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode()
    {
        int hash = 1;
        if (child_ != null) hash ^= Child.GetHashCode();
        if (NoEvents != 0) hash ^= NoEvents.GetHashCode();
        if (_unknownFields != null)
        {
            hash ^= _unknownFields.GetHashCode();
        }
        return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString()
    {
        return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output)
    {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        output.WriteRawMessage(this);
#else
    if (child_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Child);
    }
    if (NoEvents != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(NoEvents);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
    {
        if (child_ != null)
        {
            output.WriteRawTag(10);
            output.WriteMessage(Child);
        }
        if (NoEvents != 0)
        {
            output.WriteRawTag(16);
            output.WriteInt32(NoEvents);
        }
        if (_unknownFields != null)
        {
            _unknownFields.WriteTo(ref output);
        }
    }
#endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize()
    {
        int size = 0;
        if (child_ != null)
        {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Child);
        }
        if (NoEvents != 0)
        {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(NoEvents);
        }
        if (_unknownFields != null)
        {
            size += _unknownFields.CalculateSize();
        }
        return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ChildNoEventsDTO other)
    {
        if (other == null)
        {
            return;
        }
        if (other.child_ != null)
        {
            if (child_ == null)
            {
                Child = new global::Child();
            }
            Child.MergeFrom(other.Child);
        }
        if (other.NoEvents != 0)
        {
            NoEvents = other.NoEvents;
        }
        _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input)
    {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        input.ReadRawMessage(this);
#else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (child_ == null) {
            Child = new global::Child();
          }
          input.ReadMessage(Child);
          break;
        }
        case 16: {
          NoEvents = input.ReadInt32();
          break;
        }
      }
    }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                    break;
                case 10:
                    {
                        if (child_ == null)
                        {
                            Child = new global::Child();
                        }
                        input.ReadMessage(Child);
                        break;
                    }
                case 16:
                    {
                        NoEvents = input.ReadInt32();
                        break;
                    }
            }
        }
    }
#endif

}

public sealed partial class EventAgeGroupDTO : pb::IMessage<EventAgeGroupDTO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
    private static readonly pb::MessageParser<EventAgeGroupDTO> _parser = new pb::MessageParser<EventAgeGroupDTO>(() => new EventAgeGroupDTO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EventAgeGroupDTO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor
    {
        get { return global::ProtocolV3Reflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor
    {
        get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EventAgeGroupDTO()
    {
        OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EventAgeGroupDTO(EventAgeGroupDTO other) : this()
    {
        event_ = other.event_;
        ageGroup_ = other.ageGroup_;
        _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EventAgeGroupDTO Clone()
    {
        return new EventAgeGroupDTO(this);
    }

    /// <summary>Field number for the "event" field.</summary>
    public const int EventFieldNumber = 1;
    private global::Event event_ = global::Event.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Event Event
    {
        get { return event_; }
        set
        {
            event_ = value;
        }
    }

    /// <summary>Field number for the "ageGroup" field.</summary>
    public const int AgeGroupFieldNumber = 2;
    private global::AgeGroup ageGroup_ = global::AgeGroup.A68Y;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::AgeGroup AgeGroup
    {
        get { return ageGroup_; }
        set
        {
            ageGroup_ = value;
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other)
    {
        return Equals(other as EventAgeGroupDTO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EventAgeGroupDTO other)
    {
        if (ReferenceEquals(other, null))
        {
            return false;
        }
        if (ReferenceEquals(other, this))
        {
            return true;
        }
        if (Event != other.Event) return false;
        if (AgeGroup != other.AgeGroup) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode()
    {
        int hash = 1;
        if (Event != global::Event.None) hash ^= Event.GetHashCode();
        if (AgeGroup != global::AgeGroup.A68Y) hash ^= AgeGroup.GetHashCode();
        if (_unknownFields != null)
        {
            hash ^= _unknownFields.GetHashCode();
        }
        return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString()
    {
        return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output)
    {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        output.WriteRawMessage(this);
#else
    if (Event != global::Event.None) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Event);
    }
    if (AgeGroup != global::AgeGroup.A68Y) {
      output.WriteRawTag(16);
      output.WriteEnum((int) AgeGroup);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
    {
        if (Event != global::Event.None)
        {
            output.WriteRawTag(8);
            output.WriteEnum((int)Event);
        }
        if (AgeGroup != global::AgeGroup.A68Y)
        {
            output.WriteRawTag(16);
            output.WriteEnum((int)AgeGroup);
        }
        if (_unknownFields != null)
        {
            _unknownFields.WriteTo(ref output);
        }
    }
#endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize()
    {
        int size = 0;
        if (Event != global::Event.None)
        {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int)Event);
        }
        if (AgeGroup != global::AgeGroup.A68Y)
        {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int)AgeGroup);
        }
        if (_unknownFields != null)
        {
            size += _unknownFields.CalculateSize();
        }
        return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EventAgeGroupDTO other)
    {
        if (other == null)
        {
            return;
        }
        if (other.Event != global::Event.None)
        {
            Event = other.Event;
        }
        if (other.AgeGroup != global::AgeGroup.A68Y)
        {
            AgeGroup = other.AgeGroup;
        }
        _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input)
    {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        input.ReadRawMessage(this);
#else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Event = (global::Event) input.ReadEnum();
          break;
        }
        case 16: {
          AgeGroup = (global::AgeGroup) input.ReadEnum();
          break;
        }
      }
    }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                    break;
                case 8:
                    {
                        Event = (global::Event)input.ReadEnum();
                        break;
                    }
                case 16:
                    {
                        AgeGroup = (global::AgeGroup)input.ReadEnum();
                        break;
                    }
            }
        }
    }
#endif

}

public sealed partial class EventCountDTO : pb::IMessage<EventCountDTO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
    private static readonly pb::MessageParser<EventCountDTO> _parser = new pb::MessageParser<EventCountDTO>(() => new EventCountDTO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EventCountDTO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor
    {
        get { return global::ProtocolV3Reflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor
    {
        get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EventCountDTO()
    {
        OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EventCountDTO(EventCountDTO other) : this()
    {
        event_ = other.event_;
        ageGroup_ = other.ageGroup_;
        count_ = other.count_;
        _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EventCountDTO Clone()
    {
        return new EventCountDTO(this);
    }

    /// <summary>Field number for the "event" field.</summary>
    public const int EventFieldNumber = 1;
    private global::Event event_ = global::Event.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Event Event
    {
        get { return event_; }
        set
        {
            event_ = value;
        }
    }

    /// <summary>Field number for the "ageGroup" field.</summary>
    public const int AgeGroupFieldNumber = 2;
    private global::AgeGroup ageGroup_ = global::AgeGroup.A68Y;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::AgeGroup AgeGroup
    {
        get { return ageGroup_; }
        set
        {
            ageGroup_ = value;
        }
    }

    /// <summary>Field number for the "count" field.</summary>
    public const int CountFieldNumber = 3;
    private long count_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Count
    {
        get { return count_; }
        set
        {
            count_ = value;
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other)
    {
        return Equals(other as EventCountDTO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EventCountDTO other)
    {
        if (ReferenceEquals(other, null))
        {
            return false;
        }
        if (ReferenceEquals(other, this))
        {
            return true;
        }
        if (Event != other.Event) return false;
        if (AgeGroup != other.AgeGroup) return false;
        if (Count != other.Count) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode()
    {
        int hash = 1;
        if (Event != global::Event.None) hash ^= Event.GetHashCode();
        if (AgeGroup != global::AgeGroup.A68Y) hash ^= AgeGroup.GetHashCode();
        if (Count != 0L) hash ^= Count.GetHashCode();
        if (_unknownFields != null)
        {
            hash ^= _unknownFields.GetHashCode();
        }
        return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString()
    {
        return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output)
    {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        output.WriteRawMessage(this);
#else
    if (Event != global::Event.None) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Event);
    }
    if (AgeGroup != global::AgeGroup.A68Y) {
      output.WriteRawTag(16);
      output.WriteEnum((int) AgeGroup);
    }
    if (Count != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(Count);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
    {
        if (Event != global::Event.None)
        {
            output.WriteRawTag(8);
            output.WriteEnum((int)Event);
        }
        if (AgeGroup != global::AgeGroup.A68Y)
        {
            output.WriteRawTag(16);
            output.WriteEnum((int)AgeGroup);
        }
        if (Count != 0L)
        {
            output.WriteRawTag(24);
            output.WriteInt64(Count);
        }
        if (_unknownFields != null)
        {
            _unknownFields.WriteTo(ref output);
        }
    }
#endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize()
    {
        int size = 0;
        if (Event != global::Event.None)
        {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int)Event);
        }
        if (AgeGroup != global::AgeGroup.A68Y)
        {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int)AgeGroup);
        }
        if (Count != 0L)
        {
            size += 1 + pb::CodedOutputStream.ComputeInt64Size(Count);
        }
        if (_unknownFields != null)
        {
            size += _unknownFields.CalculateSize();
        }
        return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EventCountDTO other)
    {
        if (other == null)
        {
            return;
        }
        if (other.Event != global::Event.None)
        {
            Event = other.Event;
        }
        if (other.AgeGroup != global::AgeGroup.A68Y)
        {
            AgeGroup = other.AgeGroup;
        }
        if (other.Count != 0L)
        {
            Count = other.Count;
        }
        _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input)
    {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        input.ReadRawMessage(this);
#else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Event = (global::Event) input.ReadEnum();
          break;
        }
        case 16: {
          AgeGroup = (global::AgeGroup) input.ReadEnum();
          break;
        }
        case 24: {
          Count = input.ReadInt64();
          break;
        }
      }
    }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                    break;
                case 8:
                    {
                        Event = (global::Event)input.ReadEnum();
                        break;
                    }
                case 16:
                    {
                        AgeGroup = (global::AgeGroup)input.ReadEnum();
                        break;
                    }
                case 24:
                    {
                        Count = input.ReadInt64();
                        break;
                    }
            }
        }
    }
#endif

}

public sealed partial class Request : pb::IMessage<Request>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
    private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor
    {
        get { return global::ProtocolV3Reflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor
    {
        get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Request()
    {
        OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Request(Request other) : this()
    {
        type_ = other.type_;
        user_ = other.user_ != null ? other.user_.Clone() : null;
        eag_ = other.eag_ != null ? other.eag_.Clone() : null;
        pd_ = other.pd_ != null ? other.pd_.Clone() : null;
        _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Request Clone()
    {
        return new Request(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Request.Types.Type type_ = global::Request.Types.Type.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Request.Types.Type Type
    {
        get { return type_; }
        set
        {
            type_ = value;
        }
    }

    /// <summary>Field number for the "user" field.</summary>
    public const int UserFieldNumber = 2;
    private global::User user_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::User User
    {
        get { return user_; }
        set
        {
            user_ = value;
        }
    }

    /// <summary>Field number for the "eag" field.</summary>
    public const int EagFieldNumber = 3;
    private global::EventAgeGroupDTO eag_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::EventAgeGroupDTO Eag
    {
        get { return eag_; }
        set
        {
            eag_ = value;
        }
    }

    /// <summary>Field number for the "pd" field.</summary>
    public const int PdFieldNumber = 4;
    private global::ParticipantDetailsDTO pd_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ParticipantDetailsDTO Pd
    {
        get { return pd_; }
        set
        {
            pd_ = value;
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other)
    {
        return Equals(other as Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Request other)
    {
        if (ReferenceEquals(other, null))
        {
            return false;
        }
        if (ReferenceEquals(other, this))
        {
            return true;
        }
        if (Type != other.Type) return false;
        if (!object.Equals(User, other.User)) return false;
        if (!object.Equals(Eag, other.Eag)) return false;
        if (!object.Equals(Pd, other.Pd)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode()
    {
        int hash = 1;
        if (Type != global::Request.Types.Type.Unknown) hash ^= Type.GetHashCode();
        if (user_ != null) hash ^= User.GetHashCode();
        if (eag_ != null) hash ^= Eag.GetHashCode();
        if (pd_ != null) hash ^= Pd.GetHashCode();
        if (_unknownFields != null)
        {
            hash ^= _unknownFields.GetHashCode();
        }
        return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString()
    {
        return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output)
    {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        output.WriteRawMessage(this);
#else
    if (Type != global::Request.Types.Type.Unknown) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (user_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(User);
    }
    if (eag_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(Eag);
    }
    if (pd_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(Pd);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
    {
        if (Type != global::Request.Types.Type.Unknown)
        {
            output.WriteRawTag(8);
            output.WriteEnum((int)Type);
        }
        if (user_ != null)
        {
            output.WriteRawTag(18);
            output.WriteMessage(User);
        }
        if (eag_ != null)
        {
            output.WriteRawTag(26);
            output.WriteMessage(Eag);
        }
        if (pd_ != null)
        {
            output.WriteRawTag(34);
            output.WriteMessage(Pd);
        }
        if (_unknownFields != null)
        {
            _unknownFields.WriteTo(ref output);
        }
    }
#endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize()
    {
        int size = 0;
        if (Type != global::Request.Types.Type.Unknown)
        {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int)Type);
        }
        if (user_ != null)
        {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(User);
        }
        if (eag_ != null)
        {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Eag);
        }
        if (pd_ != null)
        {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pd);
        }
        if (_unknownFields != null)
        {
            size += _unknownFields.CalculateSize();
        }
        return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Request other)
    {
        if (other == null)
        {
            return;
        }
        if (other.Type != global::Request.Types.Type.Unknown)
        {
            Type = other.Type;
        }
        if (other.user_ != null)
        {
            if (user_ == null)
            {
                User = new global::User();
            }
            User.MergeFrom(other.User);
        }
        if (other.eag_ != null)
        {
            if (eag_ == null)
            {
                Eag = new global::EventAgeGroupDTO();
            }
            Eag.MergeFrom(other.Eag);
        }
        if (other.pd_ != null)
        {
            if (pd_ == null)
            {
                Pd = new global::ParticipantDetailsDTO();
            }
            Pd.MergeFrom(other.Pd);
        }
        _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input)
    {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        input.ReadRawMessage(this);
#else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Type = (global::Request.Types.Type) input.ReadEnum();
          break;
        }
        case 18: {
          if (user_ == null) {
            User = new global::User();
          }
          input.ReadMessage(User);
          break;
        }
        case 26: {
          if (eag_ == null) {
            Eag = new global::EventAgeGroupDTO();
          }
          input.ReadMessage(Eag);
          break;
        }
        case 34: {
          if (pd_ == null) {
            Pd = new global::ParticipantDetailsDTO();
          }
          input.ReadMessage(Pd);
          break;
        }
      }
    }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                    break;
                case 8:
                    {
                        Type = (global::Request.Types.Type)input.ReadEnum();
                        break;
                    }
                case 18:
                    {
                        if (user_ == null)
                        {
                            User = new global::User();
                        }
                        input.ReadMessage(User);
                        break;
                    }
                case 26:
                    {
                        if (eag_ == null)
                        {
                            Eag = new global::EventAgeGroupDTO();
                        }
                        input.ReadMessage(Eag);
                        break;
                    }
                case 34:
                    {
                        if (pd_ == null)
                        {
                            Pd = new global::ParticipantDetailsDTO();
                        }
                        input.ReadMessage(Pd);
                        break;
                    }
            }
        }
    }
#endif

    #region Nested types
    /// <summary>Container for nested types declared in the Request message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types
    {
        public enum Type
        {
            [pbr::OriginalName("UNKNOWN")] Unknown = 0,
            [pbr::OriginalName("LOGIN")] Login = 1,
            [pbr::OriginalName("LOGOUT")] Logout = 2,
            [pbr::OriginalName("CHILDREN_EVENTS")] ChildrenEvents = 3,
            [pbr::OriginalName("ADD_PARTICIPANT")] AddParticipant = 4,
            [pbr::OriginalName("EVENT_COUNT")] EventCount = 5,
        }

    }
    #endregion

}

public sealed partial class Response : pb::IMessage<Response>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
    private static readonly pb::MessageParser<Response> _parser = new pb::MessageParser<Response>(() => new Response());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor
    {
        get { return global::ProtocolV3Reflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor
    {
        get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Response()
    {
        OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Response(Response other) : this()
    {
        type_ = other.type_;
        error_ = other.error_;
        ec_ = other.ec_.Clone();
        cne_ = other.cne_.Clone();
        _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Response Clone()
    {
        return new Response(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Response.Types.Type type_ = global::Response.Types.Type.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Response.Types.Type Type
    {
        get { return type_; }
        set
        {
            type_ = value;
        }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 2;
    private string error_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Error
    {
        get { return error_; }
        set
        {
            error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        }
    }

    /// <summary>Field number for the "ec" field.</summary>
    public const int EcFieldNumber = 3;
    private static readonly pb::FieldCodec<global::EventCountDTO> _repeated_ec_codec
        = pb::FieldCodec.ForMessage(26, global::EventCountDTO.Parser);
    private readonly pbc::RepeatedField<global::EventCountDTO> ec_ = new pbc::RepeatedField<global::EventCountDTO>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::EventCountDTO> Ec
    {
        get { return ec_; }
    }

    /// <summary>Field number for the "cne" field.</summary>
    public const int CneFieldNumber = 4;
    private static readonly pb::FieldCodec<global::ChildNoEventsDTO> _repeated_cne_codec
        = pb::FieldCodec.ForMessage(34, global::ChildNoEventsDTO.Parser);
    private readonly pbc::RepeatedField<global::ChildNoEventsDTO> cne_ = new pbc::RepeatedField<global::ChildNoEventsDTO>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::ChildNoEventsDTO> Cne
    {
        get { return cne_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other)
    {
        return Equals(other as Response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Response other)
    {
        if (ReferenceEquals(other, null))
        {
            return false;
        }
        if (ReferenceEquals(other, this))
        {
            return true;
        }
        if (Type != other.Type) return false;
        if (Error != other.Error) return false;
        if (!ec_.Equals(other.ec_)) return false;
        if (!cne_.Equals(other.cne_)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode()
    {
        int hash = 1;
        if (Type != global::Response.Types.Type.Unknown) hash ^= Type.GetHashCode();
        if (Error.Length != 0) hash ^= Error.GetHashCode();
        hash ^= ec_.GetHashCode();
        hash ^= cne_.GetHashCode();
        if (_unknownFields != null)
        {
            hash ^= _unknownFields.GetHashCode();
        }
        return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString()
    {
        return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output)
    {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        output.WriteRawMessage(this);
#else
    if (Type != global::Response.Types.Type.Unknown) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (Error.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Error);
    }
    ec_.WriteTo(output, _repeated_ec_codec);
    cne_.WriteTo(output, _repeated_cne_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
    {
        if (Type != global::Response.Types.Type.Unknown)
        {
            output.WriteRawTag(8);
            output.WriteEnum((int)Type);
        }
        if (Error.Length != 0)
        {
            output.WriteRawTag(18);
            output.WriteString(Error);
        }
        ec_.WriteTo(ref output, _repeated_ec_codec);
        cne_.WriteTo(ref output, _repeated_cne_codec);
        if (_unknownFields != null)
        {
            _unknownFields.WriteTo(ref output);
        }
    }
#endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize()
    {
        int size = 0;
        if (Type != global::Response.Types.Type.Unknown)
        {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int)Type);
        }
        if (Error.Length != 0)
        {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
        }
        size += ec_.CalculateSize(_repeated_ec_codec);
        size += cne_.CalculateSize(_repeated_cne_codec);
        if (_unknownFields != null)
        {
            size += _unknownFields.CalculateSize();
        }
        return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Response other)
    {
        if (other == null)
        {
            return;
        }
        if (other.Type != global::Response.Types.Type.Unknown)
        {
            Type = other.Type;
        }
        if (other.Error.Length != 0)
        {
            Error = other.Error;
        }
        ec_.Add(other.ec_);
        cne_.Add(other.cne_);
        _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input)
    {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        input.ReadRawMessage(this);
#else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Type = (global::Response.Types.Type) input.ReadEnum();
          break;
        }
        case 18: {
          Error = input.ReadString();
          break;
        }
        case 26: {
          ec_.AddEntriesFrom(input, _repeated_ec_codec);
          break;
        }
        case 34: {
          cne_.AddEntriesFrom(input, _repeated_cne_codec);
          break;
        }
      }
    }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                    break;
                case 8:
                    {
                        Type = (global::Response.Types.Type)input.ReadEnum();
                        break;
                    }
                case 18:
                    {
                        Error = input.ReadString();
                        break;
                    }
                case 26:
                    {
                        ec_.AddEntriesFrom(ref input, _repeated_ec_codec);
                        break;
                    }
                case 34:
                    {
                        cne_.AddEntriesFrom(ref input, _repeated_cne_codec);
                        break;
                    }
            }
        }
    }
#endif

    #region Nested types
    /// <summary>Container for nested types declared in the Response message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types
    {
        public enum Type
        {
            [pbr::OriginalName("UNKNOWN")] Unknown = 0,
            [pbr::OriginalName("OK")] Ok = 1,
            [pbr::OriginalName("ERROR")] Error = 2,
            [pbr::OriginalName("CHILDREN_EVENTS")] ChildrenEvents = 3,
            [pbr::OriginalName("EVENT_COUNT")] EventCount = 4,
            [pbr::OriginalName("REFRESH_EVENTS")] RefreshEvents = 5,
        }

    }
    #endregion

}

#endregion


#endregion Designer generated code
